# -*- coding: utf-8 -*-
"""Bibliotecas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZCwd_9JLa_dQj0tOhRou44UpPGC67XMQ
"""

Flask
redirect 
url_for
request
render_template
get
BeautifulSoup4
warn
sleep
randint
numpy
pandas
seaborn
time-tools
random